--
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO public;

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: check_matching_tagtype(); Type: FUNCTION; Schema: public; Owner: bjorn
--

CREATE FUNCTION public.check_matching_tagtype() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF (NEW.tagtype_id IS DISTINCT FROM (SELECT tagtype_id FROM public.tagsets WHERE id = NEW.tagset_id)) THEN
        RAISE EXCEPTION 'Tagtype_id does not match the corresponding tagset''s tagtype_id';
    END IF;
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.check_matching_tagtype() OWNER TO postgres;

--
-- Name: check_nodes_tagset(); Type: FUNCTION; Schema: public; Owner: bjorn
--

CREATE FUNCTION public.check_nodes_tagset() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
DECLARE
  tagset_id_for_hierarchy INTEGER;
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM public.tags t 
    JOIN (SELECT tagset_id FROM public.hierarchies WHERE id = NEW.hierarchy_id) h
    ON t.tagset_id = h.tagset_id
    WHERE t.id = NEW.tag_id
  ) THEN
    RAISE EXCEPTION 'The tag_id does not belong to the correct tagset_id for this hierarchy.';
  END IF;
  RETURN NEW;
END;
$$;


ALTER FUNCTION public.check_nodes_tagset() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: nodes; Type: TABLE; Schema: public; Owner: bjorn
--

CREATE TABLE public.nodes (
    id integer NOT NULL,
    tag_id integer NOT NULL,
    hierarchy_id integer NOT NULL,
    parentnode_id integer
);


ALTER TABLE public.nodes OWNER TO postgres;

--
-- Name: get_level_from_parent_node(integer, integer); Type: FUNCTION; Schema: public; Owner: bjorn
--

CREATE FUNCTION public.get_level_from_parent_node(integer, integer) RETURNS SETOF public.nodes
    LANGUAGE sql
    AS $_$
    select N.id, N.tag_id, N.hierarchy_id, N.parentnode_id
	from public.nodes N 
	where N.parentnode_id = $1 and N.hierarchy_id = $2
$_$;


ALTER FUNCTION public.get_level_from_parent_node(integer, integer) OWNER TO postgres;

--
-- Name: get_level_from_sibling(integer, integer); Type: FUNCTION; Schema: public; Owner: bjorn
--

CREATE FUNCTION public.get_level_from_sibling(integer, integer) RETURNS SETOF public.nodes
    LANGUAGE sql
    AS $_$
    select N.id, N.tag_id, N.hierarchy_id, N.parentnode_id
	from public.nodes N 
		join public.nodes N1 on N.parentnode_id = N1.parentnode_id
	where N1.id = $1 and N1.hierarchy_id = $2
$_$;


ALTER FUNCTION public.get_level_from_sibling(integer, integer) OWNER TO postgres;

--
-- Name: get_subtree_from_parent_node(integer); Type: FUNCTION; Schema: public; Owner: bjorn
--

CREATE FUNCTION public.get_subtree_from_parent_node(integer) RETURNS SETOF public.nodes
    LANGUAGE sql
    AS $_$
WITH RECURSIVE allsubtags AS(
    select N.id, N.tag_id, N.hierarchy_id, N.parentnode_id
	from public.nodes N 
	where N.id = $1
    UNION ALL
    select N.id, N.tag_id, N.hierarchy_id, N.parentnode_id
	from public.nodes N
		join allsubtags A on A.id = N.parentnode_id
)  select * from allsubtags
$_$;


ALTER FUNCTION public.get_subtree_from_parent_node(integer) OWNER TO postgres;

--
-- Name: alphanumerical_tags; Type: TABLE; Schema: public; Owner: bjorn
--

CREATE TABLE public.alphanumerical_tags (
    id integer NOT NULL,
    name text NOT NULL,
    tagset_id integer NOT NULL
);


ALTER TABLE public.alphanumerical_tags OWNER TO postgres;

--
-- Name: date_tags; Type: TABLE; Schema: public; Owner: bjorn
--

CREATE TABLE public.date_tags (
    id integer NOT NULL,
    name date NOT NULL,
    tagset_id integer NOT NULL
);


ALTER TABLE public.date_tags OWNER TO postgres;

--
-- Name: hierarchies; Type: TABLE; Schema: public; Owner: bjorn
--

CREATE TABLE public.hierarchies (
    id integer NOT NULL,
    name text NOT NULL,
    tagset_id integer NOT NULL,
    rootnode_id integer
);


ALTER TABLE public.hierarchies OWNER TO postgres;

--
-- Name: hierarchies_id_seq; Type: SEQUENCE; Schema: public; Owner: bjorn
--

ALTER TABLE public.hierarchies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hierarchies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medias; Type: TABLE; Schema: public; Owner: bjorn
--

CREATE TABLE public.medias (
    id integer NOT NULL,
    file_uri text NOT NULL,
    file_type integer NOT NULL,
    thumbnail_uri text
);


ALTER TABLE public.medias OWNER TO postgres;

--
-- Name: medias_id_seq; Type: SEQUENCE; Schema: public; Owner: bjorn
--

ALTER TABLE public.medias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nodes_id_seq; Type: SEQUENCE; Schema: public; Owner: bjorn
--

ALTER TABLE public.nodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: taggings; Type: TABLE; Schema: public; Owner: bjorn
--

CREATE TABLE public.taggings (
    object_id integer NOT NULL,
    tag_id integer NOT NULL
);


ALTER TABLE public.taggings OWNER TO postgres;

--
-- Name: nodes_taggings; Type:  VIEW; Schema: public; Owner: bjorn
--

CREATE VIEW public.nodes_taggings AS
 SELECT h.parentnode_id,
    h.id AS node_id,
    h.tag_id,
    r.object_id
   FROM (( SELECT n.parentnode_id,
            n.id,
            (public.get_subtree_from_parent_node(n.id)).tag_id AS tag_id
           FROM public.nodes n) h
     JOIN public.taggings r ON ((r.tag_id = h.tag_id)))
  ;


ALTER TABLE public.nodes_taggings OWNER TO postgres;

--
-- Name: numerical_tags; Type: TABLE; Schema: public; Owner: bjorn
--

CREATE TABLE public.numerical_tags (
    id integer NOT NULL,
    name integer NOT NULL,
    tagset_id integer NOT NULL
);


ALTER TABLE public.numerical_tags OWNER TO postgres;

--
-- Name: tag_types; Type: TABLE; Schema: public; Owner: bjorn
--

CREATE TABLE public.tag_types (
    id integer NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.tag_types OWNER TO postgres;

--
-- Name: tag_types_id_seq; Type: SEQUENCE; Schema: public; Owner: bjorn
--

ALTER TABLE public.tag_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tag_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tags; Type: TABLE; Schema: public; Owner: bjorn
--

CREATE TABLE public.tags (
    id integer NOT NULL,
    tagtype_id integer NOT NULL,
    tagset_id integer NOT NULL
);


ALTER TABLE public.tags OWNER TO postgres;

--
-- Name: tags_id_seq; Type: SEQUENCE; Schema: public; Owner: bjorn
--

ALTER TABLE public.tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tagset_hierarchies; Type:  VIEW; Schema: public; Owner: bjorn
--

CREATE  VIEW public.tagset_hierarchies AS
 SELECT hierarchies.id,
    hierarchies.name,
    hierarchies.tagset_id AS tagsetid,
    1 AS tagtypeid,
    NULL::text AS nodes,
    hierarchies.rootnode_id AS rootnodeid
   FROM public.hierarchies;


ALTER TABLE public.tagset_hierarchies OWNER TO postgres;

--
-- Name: time_tags; Type: TABLE; Schema: public; Owner: bjorn
--

CREATE TABLE public.time_tags (
    id integer NOT NULL,
    name time without time zone NOT NULL,
    tagset_id integer NOT NULL
);


ALTER TABLE public.time_tags OWNER TO postgres;

--
-- Name: timestamp_tags; Type: TABLE; Schema: public; Owner: bjorn
--

CREATE TABLE public.timestamp_tags (
    id integer NOT NULL,
    name timestamp without time zone NOT NULL,
    tagset_id integer NOT NULL
);


ALTER TABLE public.timestamp_tags OWNER TO postgres;

--
-- Name: tagset_tags; Type:  VIEW; Schema: public; Owner: bjorn
--

CREATE  VIEW public.tagset_tags AS
 SELECT alphanumerical_tags.id,
    (alphanumerical_tags.name)::character varying AS name,
    alphanumerical_tags.tagset_id AS tagsetid,
    1 AS tagtypeid,
    NULL::text AS tagtype,
    alphanumerical_tags.tagset_id AS tagsetidreplicate,
    NULL::text AS objecttagrelations
   FROM public.alphanumerical_tags
UNION ALL
 SELECT timestamp_tags.id,
    (timestamp_tags.name)::character varying AS name,
    timestamp_tags.tagset_id AS tagsetid,
    2 AS tagtypeid,
    NULL::text AS tagtype,
    timestamp_tags.tagset_id AS tagsetidreplicate,
    NULL::text AS objecttagrelations
   FROM public.timestamp_tags
UNION ALL
 SELECT time_tags.id,
    (time_tags.name)::character varying AS name,
    time_tags.tagset_id AS tagsetid,
    3 AS tagtypeid,
    NULL::text AS tagtype,
    time_tags.tagset_id AS tagsetidreplicate,
    NULL::text AS objecttagrelations
   FROM public.time_tags
UNION ALL
 SELECT date_tags.id,
    (date_tags.name)::character varying AS name,
    date_tags.tagset_id AS tagsetid,
    4 AS tagtypeid,
    NULL::text AS tagtype,
    date_tags.tagset_id AS tagsetidreplicate,
    NULL::text AS objecttagrelations
   FROM public.date_tags
UNION ALL
 SELECT numerical_tags.id,
    (numerical_tags.name)::character varying AS name,
    numerical_tags.tagset_id AS tagsetid,
    5 AS tagtypeid,
    NULL::text AS tagtype,
    numerical_tags.tagset_id AS tagsetidreplicate,
    NULL::text AS objecttagrelations
   FROM public.numerical_tags
  ;


ALTER TABLE public.tagset_tags OWNER TO postgres;

--
-- Name: tagsets; Type: TABLE; Schema: public; Owner: bjorn
--

CREATE TABLE public.tagsets (
    id integer NOT NULL,
    name text NOT NULL,
    tagtype_id integer NOT NULL
);


ALTER TABLE public.tagsets OWNER TO postgres;

--
-- Name: tagsets_id_seq; Type: SEQUENCE; Schema: public; Owner: bjorn
--

ALTER TABLE public.tagsets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tagsets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tagsets_taggings; Type:  VIEW; Schema: public; Owner: bjorn
--

CREATE  VIEW public.tagsets_taggings AS
 SELECT t.tagset_id,
    r.tag_id,
    r.object_id
   FROM (public.tags t
     JOIN public.taggings r ON ((r.tag_id = t.id)))
  ;


ALTER TABLE public.tagsets_taggings OWNER TO postgres;
